### ISSUE TITLE
[BUG] Plasma Boxes Aren't Powerful Enough

### ISSUE THREAD

**Issue by iJutomi** [HumanGamer/WPlusIssues#10]
While wooden boxes and metal boxes seem to work fine, plasma boxes are weak.

Firstly, they don't push other plasma boxes when on ice (presumable also true for conveyors).

![image](https://user-images.githubusercontent.com/92065817/148624755-c5ea8f80-da08-4ec5-9e81-7c5a97a156f8.png)
_A plasma box bouncing between two other plasma boxes._

Secondly, normally when a weaker box is smashed into by a moving, stronger box, it moves. This is correct. However, when said weaker box cannot move, it should be destroyed. This works when a steel box smashes into a wooden box, however plasma boxes will simply bounce off of the immobile metal box. In fact, they will straightup bounce off of immobile wood boxes too.

![image](https://user-images.githubusercontent.com/92065817/148624760-09fba6c4-e17b-4e77-afe3-33b079f73ec7.png)
_Loof getting creamed by a plasma box bouncing off of a wooden box_

In addition, plasma boxes will simply bounce off of gummy blocks, however this actually IS how they behave in vanilla.

Other boxes seem to work as intended, however; it seems like an issue specifically with plasma boxes. That said, I have not tried all of them. What's interesting is that this behavior is actually what does happen with gummy blocks and mobile scouges, although still slightly different (like gummy blocks break immobile wooden boxes instead of bouncing off of them). 

As of Commit 4d68c80

**Comment by iJutomi** [comment]
Added last paragraph to issue

**Comment by ALEXM99999** [comment]
Fixed in commit e6ed8f0a
