### ISSUE TITLE
[BUG] Adjacent Teleporter Infinitum Bug

### ISSUE THREAD

**Issue by iJutomi** [HumanGamer/WPlusIssues#13]
This is a very mild collision issue. So say you have this set up: a wall, followed by two transporters of the same color, followed by a stinker.

![image](https://user-images.githubusercontent.com/92065817/148625671-c35a240f-1562-48e5-8052-8380582be3e0.png)

In vanilla, when you move left, the strangest thing happens; you point upwards.

![image](https://user-images.githubusercontent.com/92065817/148625679-4945f2d8-039a-4e28-8517-ec5eae3daa9b.png)

This is probably because, collisionwise, the game thinks an object (in this case, you) is on the teleporter on the right when walking into it, and so it spits you vertically. However, this does not happen in W+

![image](https://user-images.githubusercontent.com/92065817/148625716-ccce4f74-695d-4719-ac00-b4dcda7c700a.png)

Instead, you go backwards, because the game does _not_ recognize an object as being on the teleporter. This is perhaps more accurate, but it's nonetheless different from how vanilla handles teleporters.

As of Commit 4d68c80

**Comment by ALEXM99999** [comment]
Fixed in commit 5659a221
