### ISSUE TITLE
[INQUIRY] Music Names Mixed?

### ISSUE THREAD

**Issue by iJutomi** [HumanGamer/WPlusIssues#14]
In the editor, music track 2 is called "waterwaves" while music track 3 is called "puzzling breeze".

This might be a small nitpick, but generally track 2 often feels more like "puzzling breeze" and track 3 feels like "waterwaves".

I'm not sure if this is important, and it's entirely possible this is how it's _supposed_ to be, but often times track 2 is shorthanded as "puzzle" / "wondertown" and track 3 is shorthanded as "plains" / "pastoral", or generally watery. I wouldn't be surprised if the existing names are in fact what they're supposed to be, and if they are don't change them; however, if it's strictly for naming convention, if there's any chance the two names could be switched I think it'd be helpful.

As of Commit 4d68c80

**Comment by ALEXM99999** [comment]
Fixed in commit d3dc3a50
