### ISSUE TITLE
[BUG] Huh?ing Nonteleported Objects

### ISSUE THREAD

**Issue by iJutomi** [HumanGamer/WPlusIssues#15]
In Vanilla, when a stinker tries to enter a teleporter and they can't pop out the other side, the "Huh?" audio cue plays.

However, in W+, this happens with objects as well; i.e. every time an object tries to go through a teleporter and can't, the stinker asks "huh?" as well.

This is a minor bug and frankly doesn't need to be fixed, but it is something distinct.

**Comment by ALEXM99999** [comment]
Fixed in commit d573a982
