### ISSUE TITLE
[BUG] Flying Saucers Blocked by Certain Tiles Incorrectly

### ISSUE THREAD

**Issue by iJutomi** [HumanGamer/WPlusIssues#16]
In vanilla, UFOs / Saucers can fly over break tiles and transporters (not teleporters, mind you). In W+, they can't.

All other tiles (ice/water/lava/empty/conveyorbelts/buttons[inc. their glitch]/trampolines/tileswithmothershipsunderthem/teleporters) seem to function as intended; just specifically those two are wrong.

(Note: Tested this with ghosts, and they interact with blocks exactly how they're supposed to.)

**Comment by ALEXM99999** [comment]
Fixed in commit d573a982

**Comment by myuacc1** [comment]
A recent update seems to have unfixed this bug:
[Thu Dec 28 2023 3_36_42 PM.webm](https://github.com/HumanGamer/WPlusIssues/assets/97628479/5b9fb067-6035-4be3-882b-890395f9764e)
