### ISSUE TITLE
[BUG] Editor Can't Expand Level Size

### ISSUE THREAD

**Issue by iJutomi** [HumanGamer/WPlusIssues#18]
![image](https://user-images.githubusercontent.com/92065817/148627843-a0f13ebb-53a6-4274-940f-4a0cd978ea5f.png)

So this happened while I was trying to test something out but needed more space. I uh.

Yeah, I can't increase level sizes and then move to see the level at all. xD

(and yes I had editor scaling turned off.)

So what's interesting is this isn't actually the entire story. I actually _can_ load a level, and reduce its size. I can also _increase_ its size back all the way up to where it was.
However, I can not increase past that point. xD

As of Commit 4d68c80

**Comment by ALEXM99999** [comment]
Fixed in commit d3dc3a50
