### ISSUE TITLE
[BUG] Unrepeatable Specific Boulder+Transporter+Trampoline Glitch

### ISSUE THREAD

**Issue by iJutomi** [HumanGamer/WPlusIssues#19]
![image](https://user-images.githubusercontent.com/92065817/148628425-dfac2ce1-d48f-4bb7-8eb6-d934661db09f.png)

So... this is a really, really weird one.

So here's a video illustrating the problem: the boulder does not come back upon landing on the transporter.

https://youtu.be/-ZZ-NTJVbAc

Here's the problem: I cannot repeat this in any other environment. I'm not sure if it's _specifically_ this setup, or if it's an issue with copy/pasting levels from RTW into W+, but... yeah. It's really, really specific and I can't reproduce it anywhere except for this level.

(It's JUTOMI039: Breaking Point, if you're interested in testing it yourself.)

As of Commit 4d68c80

**Comment by iJutomi** [comment]
Updated; got links mixed up

**Comment by ALEXM99999** [comment]
Fixed in commit eb96dd9b
