### ISSUE TITLE
[REQUEST] Add BORDER/WIPE/UNDO/BLOCK

### ISSUE THREAD

**Issue by iJutomi** [HumanGamer/WPlusIssues#20]
Pretty straightforward. I'm sure you're mightily aware these features are missing.

I'm still going to complain about them not existing. ;p

![image](https://user-images.githubusercontent.com/92065817/148628493-804b66ad-3015-445e-86a1-48fdd03dd852.png)

As of Commit 4d68c80

**Comment by ALEXM99999** [comment]
Implemented as of commit 49cf0876.
