### ISSUE TITLE
[BUG] Shadow Stinkers' Extreme Time Sensitivity Thrown Out of Wack

### ISSUE THREAD

**Issue by iJutomi** [HumanGamer/WPlusIssues#23]
So, shadow stinkers are weird. It's actually true to say that some of them are slower than others (I believe up/left ones are faster than down/right ones, because of generation.)

This is extremely subtle, but important. It is the difference between a shadow stinker being able to pass through a gate while you're on a round button, and not being able to.

Why is this important? Well, it's a pain in the butt at the best of times, but the issue is in W+ it's been completely changed. For example, Muzozavr's level "No Left Turns" (filename: NOLEFTTURN) no longer works because the gates kill the uppermost shadow stinker, instead of the powder kegs, thus ruining the mechanism.

Again, it's a very confounding and frankly frustrating bug/mechanic within vanilla that simply is changed and doesn't work in W+. Not sure if it's fixable.

As of Commit 4d68c80

**Comment by ALEXM99999** [comment]
Fixed in commit 60feae76
