### ISSUE TITLE
[BUG] Fireballs Don't Cap Out; Persistent Noise Bug

### ISSUE THREAD

**Issue by iJutomi** [HumanGamer/WPlusIssues#24]
So normally, there's a maximum amount of scouge / ufo / stationary fireballs that can exist at any given time. This is done to keep the game from having difficulty performing, and in turn can be abused. Take, for example, MNIK's level Going Nuclear: Blowing the Fuse (KOOKY130), where you have to make a mechanism in order to create so many fireballs that the scouge can no longer shoot flames.

The issue is, not only is this level not solveable... but pretty quickly, the fireballs multiply so insanely fast that the game has trouble moving. I had to stop it out of fear of it crashing or worse, which brings me to my next bit of information:

There's also a noise glitch if you leave the level with this bug - and it's very similar to the one I raised in Issue #22. Other noises will also continue to play until the game processes everything.

As of Commit 4d68c80

**Comment by ALEXM99999** [comment]
Fixed in commit 449c7832
