### ISSUE TITLE
[BUG] Trampolining Out of Bounds

### ISSUE THREAD

**Issue by iJutomi** [HumanGamer/WPlusIssues#27]
So using a trampoline that sends you outside of the level - works fine. However, if you're on a trampoline while exiting the level, and you go "out of the level", you get this:

![image](https://user-images.githubusercontent.com/92065817/149607424-ca5ff95d-4396-4547-83c9-99ee4c12018d.png)
![image](https://user-images.githubusercontent.com/92065817/149607427-916dfd66-09f7-4dc7-9c61-166f97782843.png)

This could be a bug related to Issue #7 which was fixed in commit 5659a221, so this might be a non-issue; recommend testing anyway though, since I myself don't have any newer version atm.

As of commit 4d68c80

(P.S. This glitch happens as even if you're trampolining long after you've exited, say after three successful springs, etc.)

**Comment by iJutomi** [comment]
Note unrelated to bug: Conveyorbelting "out of bounds" works exactly as it should in vanilla.

**Comment by ALEXM99999** [comment]
Fixed in commit 9b6e42ac
