### ISSUE TITLE
[BUG] Trampolining Box / Idle Flame Interaction

### ISSUE THREAD

**Issue by iJutomi** [HumanGamer/WPlusIssues#28]
Complicated title, but to put it simply: in vanilla, when a player or object is trampolining, if they land on another trampoline or teleporter (or water or presumably lava; though NOT for stinkers, only other boxes) with an idle flame over it, they will NOT interact with the flame at all.

So far, everything works in W+ exactly as in Vanilla - except for one thing. When a trampolined _box_ (of any kind) lands on another trampoline with an idle flame on it, the flame interacts with that object. Interestingly, if you use a wooden box / powder keg for this, you _hear_ another "boing" as the object dies.

![image](https://user-images.githubusercontent.com/92065817/149607660-62d2208c-cca7-4e6e-afb2-f168eaa8438d.png)
_Setup for the bug in question_

As of commit 4d68c80

**Comment by ALEXM99999** [comment]
This seems to have been fixed in latest commit.
