### ISSUE TITLE
[BUG] Sound Volume is Glitchy

### ISSUE THREAD

**Issue by iJutomi** [HumanGamer/WPlusIssues#3]
Strictly for sound volume (not for music), the sound of things in-game is correct on high, but slightly off on mid and fairly off (for some things unnoticeably, for others incredibly) on low. The reason for this, I BELIEVE, is that the attack (i.e. initial punchy sound) volume on sounds is not affected by volume change, although I believe everything else is the same. That said, there could be another bug with it, but the one that strikes out to me is a non-volume-adjusted punch onset.

As of Commit 4d68c80

**Comment by iJutomi** [comment]
Status Update: It's not just menu settings. Distance to sounds also has this attribute, where something that should be quieter also sounds clippier. Again, I believe the attack remains the exact same volume while everything else is quieter, making it sound much shorter. (This was realized with fireballs bouncing off of a mirror in the far corner of the screen.)

**Comment by ALEXM99999** [comment]
This has been fixed in b0.5.0a :)
