### ISSUE TITLE
[BUG] Sticky cubes sink in lava, when they should explode.

### ISSUE THREAD

**Issue by Kamerson** [HumanGamer/WPlusIssues#30]
If you push a sticky cube into lava, normally they're supposed to explode like most objects do. However, instead they act like steel boxes and sink, acting as a bridge.

![image](https://user-images.githubusercontent.com/6343501/150044091-67cb5b95-1e78-4fa1-b8ea-8c393b608693.png)

**Comment by ALEXM99999** [comment]
This has been fixed, I just forgot to close the issue
