### ISSUE TITLE
[BUG] Two bugs involving teleporters and powder kegs

### ISSUE THREAD

**Issue by Kamerson** [HumanGamer/WPlusIssues#32]
Both of these bugs involve the interaction of an object or Stinker and a powder keg on the opposite side of the teleporter.
![image](https://user-images.githubusercontent.com/6343501/153609420-626cefb9-6dbb-40b1-a1ec-20698c002bfb.png)

The first bug involves any object entering the teleporter. In the vanilla game, if you push an object through a teleporter, it exits out the opposite side because the powder keg is in the way. However, in W+, any object exiting the opposite teleporter moves towards the powder keg, causing it to explode.

The second bug involves a Stinker entering the teleporter. In the vanilla game, if there is a wall or any other object behind the powder keg, then entering the teleporter will cause the Stinker to push the powder keg into the wall or object upon exiting the teleporter, causing the powder keg to explode and the Stinker to die immediately after walking through the teleporter. In W+, if this happens, the application crashes and comes up with the following error box:
![image](https://user-images.githubusercontent.com/6343501/153611153-3945227c-e9c2-41a0-b606-5d56b5d15013.png)

**Comment by ALEXM99999** [comment]
The first part was fixed with my fix of #39 second part apparently

**Comment by ALEXM99999** [comment]
Fixed the second part on commit dc1ee1b9.
