### ISSUE TITLE
Better Krabby Quest Editor Graphics

### ISSUE THREAD

**Issue by jdl96** [HumanGamer/WPlusIssues#33]
I've made some Krabby Quest editor graphics that might be of better quality than the ones included at the moment. I'll let you decide.
I made more than one version for some of the graphics, so feel free to choose whichever one looks the best.
They're zipped up and attached below.

[New_KQ_Editor_Graphics.zip](https://github.com/HumanGamer/WPlusIssues/files/8384507/New_KQ_Editor_Graphics.zip)

**Comment by ALEXM99999** [comment]
I used theme on commit 1c85e399, thanks!
