### ISSUE TITLE
Trampoline Bug - Player dies when following object

### ISSUE THREAD

**Issue by jdl96** [HumanGamer/WPlusIssues#34]
If the player pushes an object onto a trampoline and continues to follow it, the player will die in midair.
This bug requires the object to bounce off at least 2 trampolines.
I've made a video of it in action. The first example is showing how it's not present in RTW and the second is showing it in WDLPlus: https://www.youtube.com/watch?v=lK3Qf8O1_fc

**Comment by ALEXM99999** [comment]
Fixed on commit c50a1eac. Thanks for the reports!
