### ISSUE TITLE
[BUG] Prism sets off by itself

### ISSUE THREAD

**Issue by myuacc1** [HumanGamer/WPlusIssues#39]
I've been messing around a bit in the editor, and noticed that whenever a cannon fires in the beginning of a level, a prisim will set off by itself, despite no cannon fire hitting it. The same thing happens with the KQ prisms, as seen in the video I provided:

https://user-images.githubusercontent.com/97628479/160942557-649ec124-8d29-4998-95b1-2dde51b548ee.mp4

**Comment by myuacc1** [comment]
On another note, when a Prism is pushed into a power keg, it will instantly explode, destroying the keg alongside it.

Here's some video evidence I took:

https://user-images.githubusercontent.com/97628479/160947666-c19db707-af88-46ca-a473-4431f84866f9.mp4

(BTW: I forgot to take a video of it, but this also happens with KQ prisms....)

**Comment by ALEXM99999** [comment]
Fixed on commit 2fdad250.
