### ISSUE TITLE
[BUG] "No Music" Setting Audio Bug

### ISSUE THREAD

**Issue by iJutomi** [HumanGamer/WPlusIssues#4]
When the music is turned off, it works - for the most part. However, music does play for a split second if you switch music tracks, be it world select, going to title screen, or loading a new level in WSW / custom level.

As of Commit 4d68c80

**Comment by iJutomi** [comment]
Note: This could be a similar bug to issue #3

**Comment by ALEXM99999** [comment]
This has been fixed in b0.5.0a :)
