### ISSUE TITLE
Water Splash particle effect is shown for Trenches

### ISSUE THREAD

**Issue by jdl96** [HumanGamer/WPlusIssues#41]
When objects get pushed into trenches, the "water splash" particle effect is still shown.
This particle effect, which seems to have existed since TOW, only lasts for about a frame.
In the original games (including KQ) it seems to be mostly invisible/unused(?) because of its short duration and also because you can only see it if you're pushing objects into water that do not float.

Here is a picture:

![water_particle](https://user-images.githubusercontent.com/11260985/160945460-47009b1a-ce4e-4851-9a07-0c69952bd2ef.png)

**Comment by ALEXM99999** [comment]
Fixed on commit 1398f8df.
