### ISSUE TITLE
Placing Sign 1 after loading a level in the editor crashes the game 

### ISSUE THREAD

**Issue by jdl96** [HumanGamer/WPlusIssues#44]
Steps to reproduce:
1. Close out of the game first, then open it.
2. Go to the editor and click New Level.
3. Save the level.
4. Load the level.
5. Scroll to the Signs section and place Sign 1. The game will crash.

I also noticed that if you place a Sign other than Sign 1 for step 5, and THEN place Sign 1, sometimes the game won't crash and a random character will already be typed out in the text input screen for some reason.

**Comment by ALEXM99999** [comment]
Fixed on commit 67ddff84.
