### ISSUE TITLE
Suggestion - Krabby Quest Ice Curves

### ISSUE THREAD

**Issue by jdl96** [HumanGamer/WPlusIssues#45]
I'm not sure what is and isn't on the table for new objects/tiles, but I thought KQ Ice Curves would be a nice addition. I made some graphics for both the tiles themselves and the Editor images if you wish to use them:

[KQ Ice Curves.zip](https://github.com/HumanGamer/WPlusIssues/files/8385647/KQ.Ice.Curves.zip)

**Comment by ALEXM99999** [comment]
I added them on commit ce2d9edc. Thanks!
