### ISSUE TITLE
[BUG] UFOs in non-fake walls don't shoot

### ISSUE THREAD

**Issue by myuacc1** [HumanGamer/WPlusIssues#46]
Was playing in one of Gamer12345's Space Adventure levels and noticed that a UFO hidden inside a single non-fake wall didn't shoot, thus not setting off the mechanism that would help me finish the level in the process:

https://user-images.githubusercontent.com/97628479/161064732-eae48438-1487-4f05-87f1-b1c9778adfb1.mp4

Compare this to how it worked in Return to Wonderland:

https://user-images.githubusercontent.com/97628479/161065528-68802c64-3b13-462a-aa4e-59af23899803.mp4

**Comment by ALEXM99999** [comment]
Fixed on commit 94e854bf.
