### ISSUE TITLE
[BUG] No Music Returning from Editor

### ISSUE THREAD

**Issue by iJutomi** [HumanGamer/WPlusIssues#5]
Upon reentering the main menu from the editor (GREAT feature btw), the music does not come back. This is always the case, UNLESS you've loaded a level and tested it using F5 (GREAT feature as well). Otherwise, even if you load a level without playing F5, leave and go back to the menu, the menu music will be silent until you switch tracks via world or custom level (simply using the menu where the tracks are silent doesn't work; it has to be a track change)

As of Commit 4d68c80

**Comment by ALEXM99999** [comment]
Fixed in  commit 88d906c3
