### ISSUE TITLE
Previous keystrokes are displayed when creating a player profile

### ISSUE THREAD

**Issue by jdl96** [HumanGamer/WPlusIssues#51]
At any point when the game is open (except when in the Editor) if you start pressing letters on the keyboard and then try to create a new player profile, the name input screen will type some of the letters you pressed (usually only 1 letter but one time it typed out 2 for me).
WA has this issue as well, but it's not as bad here.

EDIT: The text input screen for Signs doesn't seem to retain letter keystrokes, but it does for the arrow keys. It's mainly for the right arrow key, causing the cursor to move 1 character to the right. Very minor.

**Comment by ALEXM99999** [comment]
Fixed on commit 5a96ed51.
