### ISSUE TITLE
Mouse inputs during testing a level can affect parts of the Editor

### ISSUE THREAD

**Issue by jdl96** [HumanGamer/WPlusIssues#53]
I was wondering why sometimes the objects section would be active after I exited testing mode, and I think I found the cause.
While testing a level, if you position the mouse over where an interactive editor element would normally be and then click, that element will process the click after exiting from testing mode. This seems to affect everything except for the area where you actually design the level.

For example, when I pause the game, the "Back To Editor" text is just over where the objects section would be. Clicking the option would then select whatever object my mouse was over upon returning to the Editor interface. For editor elements that aren't located where the pause menu options are, all the player needs to do is press F5 to exit testing mode.

If someone were to randomly click the screen for whatever reason during testing, I could imagine them being confused when returning to the Editor as to why it's asking you if you remembered to save, or why the level texture is suddenly set to something else, etc.

**Comment by ALEXM99999** [comment]
This was fixed earlier today.
