### ISSUE TITLE
Have the Playground levelset behave the same as the other levelsets

### ISSUE THREAD

**Issue by jdl96** [HumanGamer/WPlusIssues#56]
At the moment the Playground levelset has all of its levels marked as completed by default, and when you actually do beat them, it does not count towards the Levels or Total Score counters on the player profile. It also does not show golden checkmarks if the player has found all the Bonus Coins in each level. I'm aware that this is the same behavior as the original game, but it wouldn't hurt to change it so that it behaves consistently with the other levelsets.

**Comment by Aryan807** [comment]
Indeed an useful suggestion, moving Playground levelset into the select level gui was actually the first step towards doing the same.

**Comment by ALEXM99999** [comment]
Fixed on commit c83f5e98.
