### ISSUE TITLE
Incorrect File Format for Winter Tree Editor Object Graphic

### ISSUE THREAD

**Issue by jdl96** [HumanGamer/WPlusIssues#57]
I noticed that the Winter Tree object in the Editor (decoration_snow.bmp) was using the Stinky Statue graphic.
Commit a9994f0a fixed this issue, but there's a different problem now - the new file for the graphic is actually a PSD with a BMP file extension. Just wanted to report this to avoid confusion later.

**Comment by ALEXM99999** [comment]
Fixed several commits ago.
