### ISSUE TITLE
Trampolines on level border act strange

### ISSUE THREAD

**Issue by jdl96** [HumanGamer/WPlusIssues#58]
I think I'll let this video explain everything:
https://www.youtube.com/watch?v=BjIKdm7hkbA

**Comment by ALEXM99999** [comment]
This doesn't seem to happen anymore, but another bug (which apparently is a vanilla one) occurs that kills the player immediately when touching a trampoline on the level edges regardless of direction.

**Comment by ALEXM99999** [comment]
Fixed on commit 6efb5e82. This was more than one bugs actually
