### ISSUE TITLE
Game crashes when clicking on an empty spot in the Editor's Load Level screen

### ISSUE THREAD

**Issue by jdl96** [HumanGamer/WPlusIssues#59]
If you open the Load Level screen in the Editor and click on an empty spot where a level file would be, the game will crash with an error. I have attached an image of the error below.
EDIT: I'm dumb, this has nothing to do with clicking outside of the Editor rendering region.

![RUNTIME ERROR](https://user-images.githubusercontent.com/11260985/164948422-e6322c59-77c3-41ad-8dcc-f79b3cde56c5.png)

**Comment by ALEXM99999** [comment]
Fixed on commit 384e3e1e.
