### ISSUE TITLE
[BUG] Level-Size Breaking Levels Break W+ Too

### ISSUE THREAD

**Issue by iJutomi** [HumanGamer/WPlusIssues#6]
So this is not one of those glitches I think can easily be fixed, since it's not supposed to happen and somewhat breaks the vanilla game too.

So, there're two levels that are great at displaying some of the weird things that happen when you try to make a level larger than 99 tiles in one or both directions. The two that come to mind are KOOKY100 and KOOKY101.

Blocks and items become weird in these versions; they may be X or Y shifted. It's a little difficult to explain, but here's an extreme example of what happens to part of the level when you copy First Steps 48 times into a 7 x 7 grid:

![image](https://user-images.githubusercontent.com/92065817/148624946-e7e0f615-761d-4516-972d-fade4beb261b.png)
(there're many other weird things)

So the vanilla game can barely even function. But I should note that W+ cannot even open these. Perhaps that's for the best, but I thought it still worth mentioning that these levels do not even load in W+.

![image](https://user-images.githubusercontent.com/92065817/148624941-fccb976e-201c-4808-a18e-dcb30ffda06e.png)
_Error Message, very different from the usual MAV_

Furthermore, recreating the _exact_ same way in which these levels decompose in order to make this level actually winnable might be an impossibility. As such, this might just be one of those glitches that can't be resolved.

As of Commit 4d68c80

**Comment by ALEXM99999** [comment]
The crash happens because the electro tiles array has a limit of 100x100 tiles. If this is fixed, the game will load those levels fine but unlike vanilla, it doesn't seem to glitch at all so those levels may not be winnable in W+. So I don't really think this can be fixed (besides the electro array size).

**Comment by ALEXM99999** [comment]
I'm closing this as the crash issue has been fixed but it's probably impossible to make the level glitch the same way.
