### ISSUE TITLE
Stinkers die when jumping to a tile with an opened Toll Gate

### ISSUE THREAD

**Issue by jdl96** [HumanGamer/WPlusIssues#60]
This is a bug that was in the original game. If you use a trampoline to jump to a tile that has an opened Toll Gate (all Rainbow Coins collected) then the player will die. For some reason the trampoline logic seems to still be treating the tile as a Wall. I found this bug while trying to collect the Bonus Coins for the Platinum Set level "Look Before You Leap".

EDIT: This actually happens to all opened Laser Gates and KQ Seaweed Gates as well.

**Comment by ALEXM99999** [comment]
This should be fixed since commit 16032bf7.
