### ISSUE TITLE
[BUG] Circle Button & Timer Button Feature "Fixed"

### ISSUE THREAD

**Issue by Kamerson** [HumanGamer/WPlusIssues#61]
In every Wonderland game, if you step on a timer button, and stepped on & off of a circle button of the same color during the timer button's timer, the gate of that color would stay open permanently after the timer wears off. While it can be seen as a bug, it was used as a feature in WSW and quite a few custom levels.

This issue was "fixed" in W+; when the timer wears off, the gate does not open back up. This renders some custom levels and a WSW level impossible. Not every bug from the Wonderland series must remain, but this one should.

**Comment by ALEXM99999** [comment]
Fixed on commit c83f5e98.
