### ISSUE TITLE
[BUG] Clicking on a blank space when loading a level in the editor crashes the game

### ISSUE THREAD

**Issue by Kamerson** [HumanGamer/WPlusIssues#62]
In the W+ editor, if you click on Load Level and you click on any empty space below the levels, the following crash will occur:
![image](https://user-images.githubusercontent.com/6343501/179341887-72a5463f-8275-4167-b02a-d517a09419aa.png)

**Comment by ALEXM99999** [comment]
Fixed on commit 384e3e1e. (also duplicate of 59)

**Comment by Kamerson** [comment]
> Fixed on commit 384e3e1e. (also duplicate of 59)

Oh oops, sorry! I didn't look to see if the issue was already posted >.<
