### ISSUE TITLE
[BUG] Game crashes when loading a custom world and then a custom level

### ISSUE THREAD

**Issue by sarnuel** [HumanGamer/WPlusIssues#66]
This is an odd one. After loading any custom world's level (so in this case anything from _The Playground_ or _Wonderland 101_), and then going back to the custom levels list and loading any level from there (seemingly any level), the game will produce this crash:

![image](https://user-images.githubusercontent.com/52188554/197596632-13cd452f-6e2e-409a-bb3e-b2db7a2eba7d.png)

This only seems to work with loading custom levels, as this crash does not occur after loading any main-game level after a custom world's level. Same goes for games like WSW and KQ that have a non-standard world selection.

**Comment by ALEXM99999** [comment]
Fixed on commit 2800f7f1.
