### ISSUE TITLE
[BUG] Game crashes before main menu if KQ menu style is selected

### ISSUE THREAD

**Issue by HumanGamer** [HumanGamer/WPlusIssues#67]
The game throws a runtime error on startup after the loading screen if the KQ menu style is selected.

![image](https://user-images.githubusercontent.com/39096122/197690992-f4b396ef-d0bb-4e4a-928d-5d1c41ce74c2.png)

This is as of Beta 0.6.0a

**Comment by ALEXM99999** [comment]
Fixed on commit 43d5a337.
