### ISSUE TITLE
[BUG] Stinkers Die After Exiting; Interesting Win/Lose Scenario

### ISSUE THREAD

**Issue by iJutomi** [HumanGamer/WPlusIssues#7]
So this is a bit strange. Normally, when stinkers exit the exit gate, they are gone gone (safe for maybe a split second where you can bounce off of them while in the exit, AND they can in fact push objects after they've exited if they're on ice / conveyorbelt)

However, in W+ they perminently stay "alive", which means you cannot move objects into where they were.

Here's an example from Poltergeist II (JUTOMI049B). MNIK is stuck in the north part, but exits the gate by going south. Peegue then pushes a plasma box into the spot where she is, well after she's supposed to have despawned.

![image](https://user-images.githubusercontent.com/92065817/148624822-3e14936f-c867-4e10-a9b2-3619787df2a9.png)
_Peegue shoving a plasma box into what's supposed to be nothing, but instead kills Qookie after leaving the exit_

One interesting thing this does is it lets you die and win at the same time. Despite the camera panning to the dead stinker, you actually can still move! This allows you to exit while the stinker is dying. If you win this way, you will get the points for winning the level, but you will also automatically restart the level upon winning.

However, interestingly, if you're the last stinker in the game and you win, you do not die after exiting the portal (even if a kaboom! comes at you or you conveyor into a wall)

Note: Stinkers walking on or even jumping on ghost stinkers will not die. Enemies and fireballs will kill ghost stinkers though.

As of Commit 4d68c80

**Comment by iJutomi** [comment]
Put the note at the end.

**Comment by ALEXM99999** [comment]
Fixed in commit 5659a221
