### ISSUE TITLE
World Packs are not affected by the "All Worlds Unlocked" option.

### ISSUE THREAD

**Issue by jdl96** [HumanGamer/WPlusIssues#70]
Just as the title says, World Pack worlds remain locked even if the option is set otherwise.

**Comment by ALEXM99999** [comment]
"All Worlds Unlocked" unlocks all world exits except the final exit (which starts the final custscene in the case of most official sets). Both custom levelsets that are included by default have only one world, so the one and only exit is also the final exit which should only be open when the player completes all the level in the set. I also tested it with multiple worlds and it seems to work as intended.

**Comment by jdl96** [comment]
Ah, I didn't know that it worked like that. Sorry for the false report!
