### ISSUE TITLE
"The PlayGround" does not show score on "Play Custom World" menu

### ISSUE THREAD

**Issue by jdl96** [HumanGamer/WPlusIssues#72]
The custom world "The PlayGround" (playground.lvpx) shows "------" instead of the total world's score on the Play Custom World menu. I've also 100'd this particular custom world, and the gold star next to the score doesn't appear either. Wonderland 101 behaves correctly.

**Comment by ALEXM99999** [comment]
Fixed on commit 31626081. However, progress on Wonderland 101 will reset as it was not saved properly (was saved as an official world in the save file which could cause issues). Sorry about that :(
