### ISSUE TITLE
[BUG] Collapsing bridge tiles + link spheres work differently from vanilla

### ISSUE THREAD

**Issue by Rainbowmon** [HumanGamer/WPlusIssues#73]
Usually, pushing a link sphere into a collapsing bridge tile would result in the LS stopping next to it. The exception is an aerial link sphere: In vanilla, if it lands on a collapsing bridge tile after bouncing on a trampoline, it will keep rolling past the collapsing bridge tile. However, in W+, the link sphere instead breaks.

For an example, see custom level Dizzy090 "Save the Puppy": While the level is still beatable using an alternative solution in which you kill the chomper, the intended solution where you don't kill it is rendered impossible, due to the green link sphere (hidden under the powder keg) being destroyed, and thus not pressing the white button.

I'm presuming this is the same for boulders since they're similar to link spheres gameplay-wise, but the vanilla editor lags on my computer (presumably a Windows 10 issue), so I have no way of testing this without finding an example level.

**Comment by ALEXM99999** [comment]
Fixed on commit 287b084c
