### ISSUE TITLE
[BUG] Certain enemies go on breakable bridges when they shouldn't

### ISSUE THREAD

**Issue by myuacc1** [HumanGamer/WPlusIssues#78]
I noticed this bug when I played the first Coin Quest level in W+ today, where Peegue is supposed to have a grand entrance by setting off a breakable bridge which has some Z-Bots going into the water, but in the latest W+ update, The Z-Bots just go on the bridge and kill Peegue instead.

It seems that certain enemies that can't go acoss bridges, like Chompers, Kabooms, Z-Bots and even Bullies and Shadow Stinkers, can go across them without setting them off in W+:
[Wed Jan 18 2023 10_46_05 AM.webm](https://user-images.githubusercontent.com/97628479/213267855-57a0beaa-c14a-4823-8676-253070ccaedd.webm)

This seems to only work with normal tiles, but when I put bridges on water, lava or nothing, they seem to stay off bridges, which dosen't make sense considering that the bug happened in the first Coin Quest level despite it being on water:
![ijd](https://user-images.githubusercontent.com/97628479/213268474-9d1cbc6f-949f-4e5e-ab7e-bc4f4a7c617c.png)
![au](https://user-images.githubusercontent.com/97628479/213268478-80598acf-75fe-4fb7-9a89-bce48173643f.png)
(Although it seems that Z-Bots go through water regardless...)

Here's an image of the easy fix:
![aef](https://user-images.githubusercontent.com/97628479/213269398-55dd230e-ae7e-4c30-a9d1-ba1568e0fa76.png)

**Comment by ALEXM99999** [comment]
Fixed on commit 62c71074.
