### ISSUE TITLE
[BUG] Ghosts are Blocked by Bridges

### ISSUE THREAD

**Issue by sgern** [HumanGamer/WPlusIssues#79]
Ghosts are seemingly erroneously unable to move over bridges. 

As shown in [this video](https://youtu.be/9iqcdk41wFo) for Return to Wonderland Classic 3-5 "The Pendulum", they should be able to, allowing the player to collapse the bridges and trap the columns of ghosts. Currently, the left column is bunched up above the bridge, making evasion nearly impossible, and the right column is bunched up below the bridge, completely neutralizing them.

**Comment by ALEXM99999** [comment]
Fixed on commit 988028e8.
