### ISSUE TITLE
[BUG] Z-Bots Die when Hitting Bridges

### ISSUE THREAD

**Issue by sgern** [HumanGamer/WPlusIssues#80]
**Describe the bug**
In [this](https://www.pcpuzzle.com/forum/download/file.php?id=48775) custom level, the two Z-Bots hit the bridge and die instead of turning. This renders the level impossible in Wonderland Plus.

**To Reproduce**
1. Load the linked custom level in Wonderland Plus.
2. The two Z-Bots die as soon as the level starts when they hit the bridge. Pan the camera down as soon as the level starts to see it.

**Expected behavior**
They should turn, ending up with one circling the tree and the other going back and forth a bit below that.

**Comment by ALEXM99999** [comment]
This has been fixed in newer commits.
