### ISSUE TITLE
[BUG] Custom level solvable in vanilla RTW is impossible in W+

### ISSUE THREAD

**Issue by InvisibleWater** [HumanGamer/WPlusIssues#82]
In [this custom level](https://pcpuzzle.com/forum/viewtopic.php?f=11&t=13212), a steel box travels on a conveyor belt and smashes into a red link sphere, causing it to roll back and forth on conveyors until it can be destroyed with another steel box. 

In W+, the first steel box is immediately destroyed. While the red link sphere does end up in the conveyor area thanks to another red link sphere you need to push, this leaves you with nothing you can use to guide the Kabooms into the powder kegs, making the level impossible.

I am currently using version b0.7.1a.

**Comment by ALEXM99999** [comment]
Fixed on update v0.7.1b.

**Comment by InvisibleWater** [comment]
Can confirm that the level is now solvable.
