### ISSUE TITLE
[BUG] Flying Saucers Blocked by Certain Tiles Incorrectly... Again

### ISSUE THREAD

**Issue by myuacc1** [HumanGamer/WPlusIssues#84]
A recent update seems to have unfixed this bug:
[Thu Dec 28 2023 3_36_42 PM.webm](https://github.com/HumanGamer/WPlusIssues/assets/97628479/5b9fb067-6035-4be3-882b-890395f9764e)

_Originally posted by @myuacc1 in https://github.com/HumanGamer/WPlusIssues/issues/16#issuecomment-1871626387_

**Comment by ALEXM99999** [comment]
Fixed on commit d0dfa83.
